openapi: 3.0.3
info:
  title: RAG Chatbot API
  description: API for the integrated RAG chatbot system in Docusaurus book
  version: 1.0.0
  contact:
    name: RAG Chatbot Development Team
    email: team@example.com

servers:
  - url: https://api.rag-chatbot.example.com
    description: Production server
  - url: https://staging-api.rag-chatbot.example.com
    description: Staging server

paths:
  /ingest:
    post:
      summary: Ingest book content into vector store
      description: Process and store book content for RAG retrieval
      operationId: ingestContent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestRequest'
      responses:
        '200':
          description: Content successfully ingested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestResponse'
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /query:
    post:
      summary: Query the RAG system with whole-book context
      description: Ask questions about the entire book content
      operationId: queryWholeBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Query processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /query/selection:
    post:
      summary: Query the RAG system with selected text context only
      description: Ask questions constrained to only the user-selected text
      operationId: querySelection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectionQueryRequest'
      responses:
        '200':
          description: Query processed successfully with selection context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: Selection text too long (exceeds 5000 characters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check endpoint
      description: Check the health status of the RAG chatbot service
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    IngestRequest:
      type: object
      required:
        - book_id
        - title
        - content
      properties:
        book_id:
          type: string
          description: Unique identifier for the book
          example: "book-12345"
        title:
          type: string
          description: Title of the book
          example: "AI-Native Software Development Research Book"
        content:
          type: string
          description: The book content to be ingested
          example: "# Chapter 1\nThis is the content of the first chapter..."
        author:
          type: string
          description: Author of the book (optional)
          example: "John Doe"
        chunk_size:
          type: integer
          description: Size of text chunks in tokens (default 512)
          default: 512
          minimum: 100
          maximum: 1000

    IngestResponse:
      type: object
      required:
        - status
        - message
        - total_chunks
        - processing_time_ms
      properties:
        status:
          type: string
          enum: [success, error]
          example: "success"
        message:
          type: string
          description: Human-readable status message
          example: "Book content successfully ingested into vector store"
        total_chunks:
          type: integer
          description: Number of content chunks created
          example: 125
        processing_time_ms:
          type: integer
          description: Time taken to process the ingestion in milliseconds
          example: 2450

    QueryRequest:
      type: object
      required:
        - question
        - session_token
      properties:
        question:
          type: string
          description: The question to ask about the book
          example: "What are the main benefits of RAG systems?"
          minLength: 10
          maxLength: 2000
        session_token:
          type: string
          description: Session identifier for anonymous users
          example: "sess_abc123def456"
        book_id:
          type: string
          description: Optional book identifier if multiple books exist
          example: "book-12345"
        max_results:
          type: integer
          description: Maximum number of results to retrieve (default 5)
          default: 5
          minimum: 1
          maximum: 10

    SelectionQueryRequest:
      type: object
      required:
        - question
        - selected_text
        - session_token
      properties:
        question:
          type: string
          description: The question to ask about the selected text
          example: "Explain the key points in this section?"
          minLength: 10
          maxLength: 2000
        selected_text:
          type: string
          description: The text selected by the user (max 5000 chars)
          example: "RAG systems combine retrieval and generation to provide accurate answers based on specific context..."
          maxLength: 5000
        session_token:
          type: string
          description: Session identifier for anonymous users
          example: "sess_abc123def456"

    QueryResponse:
      type: object
      required:
        - answer
        - citations
        - response_time_ms
        - context_type
      properties:
        answer:
          type: string
          description: The AI-generated answer to the question
          example: "RAG systems provide several benefits including improved accuracy by grounding responses in specific context..."
        citations:
          type: array
          description: List of sources used to generate the answer
          items:
            $ref: '#/components/schemas/Citation'
        response_time_ms:
          type: integer
          description: Time taken to generate the response in milliseconds
          example: 1450
        context_type:
          type: string
          enum: [full_book, selection]
          description: Type of context used for the response
          example: "full_book"
        retrieved_chunks:
          type: array
          description: List of chunks used for context (for debugging)
          items:
            $ref: '#/components/schemas/RetrievedChunk'

    Citation:
      type: object
      required:
        - title
        - section
        - page_number
        - relevance_score
      properties:
        title:
          type: string
          description: Title of the source content
          example: "Chapter 3: Advanced RAG Techniques"
        section:
          type: string
          description: Specific section within the content
          example: "3.2 Context Retrieval Methods"
        page_number:
          type: integer
          description: Page number in the original document
          example: 45
        relevance_score:
          type: number
          description: Relevance score of the citation (0-1)
          example: 0.87
        text_preview:
          type: string
          description: Brief preview of the cited text
          example: "The context retrieval process involves searching the vector database..."

    RetrievedChunk:
      type: object
      required:
        - content
        - score
        - source
      properties:
        content:
          type: string
          description: The retrieved content chunk
          example: "RAG systems combine retrieval and generation to provide accurate answers..."
        score:
          type: number
          description: Similarity score (0-1)
          example: 0.87
        source:
          $ref: '#/components/schemas/Citation'

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
        - services
      properties:
        status:
          type: string
          enum: [healthy, degraded, unavailable]
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Current timestamp
          example: "2025-12-09T10:30:00Z"
        services:
          type: object
          description: Status of dependent services
          properties:
            vector_db:
              type: string
              enum: [available, unavailable]
              example: "available"
            llm_service:
              type: string
              enum: [available, unavailable]
              example: "available"
            database:
              type: string
              enum: [available, unavailable]
              example: "available"

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Question must be between 10 and 2000 characters"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the error
          example: "2025-12-09T10:30:00Z"
        details:
          type: object
          description: Additional error details (optional)
          example: {"field": "question", "value": "Hi"}

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Optional authentication for enhanced features

security:
  - BearerAuth: []

tags:
  - name: Ingestion
    description: Endpoints for ingesting book content
  - name: Query
    description: Endpoints for querying the RAG system
  - name: Health
    description: Health check endpoints